a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print("sum:",a+b)
print("sub:",a-b)
print("mul:",a*b)
print("div:",a/b)
print("modulo:",a%b)
print("floor:",a//b)
print("exponentiation:",a**b )
